### ISSUE TITLE
Does not start on Manjaro / Antergos

### ISSUE THREAD

**Issue by Bleuzen** [linuxdeepin/deepin-clone#10]
Hi, I try to run Deepin Clone on my Manjaro system with the KDE Plasma desktop.
Sadly I can't get it to launch.

When running from menu, I get prompted to enter my password to run as root but nothing happens. No window opens.

I launched it in a terminal and got this output:
 -> sudo deepin-clone
```
[2018-11-29, 21:00:30.501] [Warning] [=>: 0] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[2018-11-29, 21:00:30.507] [Debug  ] [dapplication.cpp=>Dtk::Widget::DApplicationPrivate::setSingleInstanceByDbus: 203] register service failed: QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
[2018-11-29, 21:00:30.507] [Error  ] [main.cpp=>main: 143] As well as the process is running
```
There is still no window. It doesn't open.

I'm currently using version 0.1.2-1 from the Archlinux repo.

Edit: I also tested it on Antergos with the Deepin desktop. Same problem there.
Now I'm not sure if this is a deepin-clone bug or a archlinux packaging bug.

**Comment by ASDFGamer** [comment]
I have the same issue with Openbox on Manjaro and the 0.1.2-1 version. It can run with user rights, but then I don't have the needed Permissions on sd(a,b,..).

**Comment by Wan-ZL** [comment]
The same thing happened to Manjaro-Deepin Environment. I can get a window with command "deepin-clone", but then Permission error happen. If I run command "sudo deepin-clone", I got:
```
[Warning] [=>: 0] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[2019-01-28, 12:23:21.464] [Debug  ] [dapplication.cpp=>Dtk::Widget::DApplicationPrivate::setSingleInstanceByDbus: 203] register service failed: QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
[2019-01-28, 12:23:21.464] [Error  ] [main.cpp=>main: 143] As well as the process is running
```

**Comment by h35jqh** [comment]
Hi I am relatively new to github. I had the same problem getting deepin-clone refusing to run on the latest Majaro Deepin with the latest updates. I found a fix that worked for me. It may work for you's. The error org.freedesktop.DBus.Error got me thinking that the problem would be in the freedesktop side. So I looked at the free desktop install options and found that the Manjaro default installation installed.
dbus  1.12.12-1  

When I installed
dbus-x11  1.12.12-1
over top of it it removed dbus 1.12.12-1 and replaced it and the deepin-clone on the apps menu ran successfully with root privilege.

Hope it helps. I did a test backup and found it worked ok for an NTFS partition and UEFI partion fat32.
Best Regards
Ed.

**Comment by KimHono** [comment]
This command is working fine without installation :
`dbus-launch --exit-with-session /usr/bin/deepin-clone`

**Comment by h35jqh** [comment]
Thanks for the tip.
Best Regards
Ed.

________________________________

**Comment by zccrs** [comment]
Hi, What version of the dbus package?

**Comment by Bleuzen** [comment]
I'm using dbus version 1.12.12-1 here.

**Comment by FFY00** [comment]
@KimHono that doesn't solve anything, that just doesn't use polkit. If you replace it with `/usr/bin/deepin-clone` it works, as expected, because polkit isn't being used. `deepin-clone-pkexec` need to be fixed. @zccrs what do you think?

**Comment by TeknoMobil** [comment]
Arch Linux Deepin, not start deepin clone..

**Comment by pranavvv** [comment]
its not working in deepin manjaro ...make it available for all platform and also deepin recovery

**Comment by FFY00** [comment]
Is anyone working on this? @felixonmars

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
