### ISSUE TITLE
Add a qmake option to disable BootDoctor, since it does not work on non-ubuntu-based distros

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/deepin-clone#11]
In BootDoctor and especially in boot_fix_x86.sh, `dpkg-query` and `ubuntu` are hard coded. It make BootDoctor obviously not working on non-ubuntu-bases distributions, like Fedora or Arch.

At best deepin-clone developers can support Fedora and Arch. But that requires some work to be done.

So at first, a qmake option is reqested, so we can disable BootDockor on non-ubuntu-bases distributions.

Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1687369

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
