### ISSUE TITLE
Unable to backup disk to image

### ISSUE THREAD

**Issue by asolopovas** [linuxdeepin/deepin-clone#19]
Hi, I am unable to create a disk image, which contains windows partitions. The message I get is "dev/nvme1n1" is used, please install "Deepin Recovery" to retry. What does it mean install Deepin Recovery, is it necessary to boot into live cd called Deepin Recovery. I can't seem to find a program with this name as well.

**Comment by BLumia** [comment]
Oh, it means you cannot do backup for the disk if your system is running and using that disk. The simplest way to do is install a recovery system and boot to that system to do backup.

If you are using Deepin distro, there is a `live-filesystem` package for you so after installation, there will be a recovery option from the grub menu, and you can use deepin-clone there.

**Comment by pranavvv** [comment]
how to install deepin recovery in manjaro deepin ??
![DeepinScreenshot_20190915133426](https://user-images.githubusercontent.com/34711035/64918474-5a48f680-d7be-11e9-8355-f3c0a6a11d2a.png)
![DeepinScreenshot_20190915112445](https://user-images.githubusercontent.com/34711035/64918475-5c12ba00-d7be-11e9-81a5-83981121919a.png)

**Comment by BLumia** [comment]
deepin-recovery is just a live system installed to your local disk, there are not a package for that purpose in manjaro, yet.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
