### ISSUE TITLE
How to reset maintainer password？

### ISSUE THREAD

**Issue by LeanderChen** [linuxdeepin/deepin-clone#23]
When I installed Deepin 15 one month ago, I found and installed deepin-clone tool. It's useful until now. I have prepared full work environment. And, I forgot my maintainer password when I prepared to clone system.  
Before Asking, I have tried these:  
1. find solutions in system, but nothing.
2. try find help in offcial forum and use keywords search, and find nothing too.

Here are my laptop and system information:
![](https://bbs.deepin.org/data/attachment/forum/201909/04/211534oudiqqyfcazriwy6.png)

**Comment by BLumia** [comment]
Did you means the deepin recovery enviroment since deepin-clone itself doesn't have a "maintainer password"?

**Comment by LeanderChen** [comment]
Yes. Also, it may be called "deepin live" which is booted as "deepin recovery".
This issue was posted on [offcial forum](https://bbs.deepin.org/forum.php?mod=viewthread&tid=182411). It seems to be nothing helpful too.

This is the login page of "deepin recovery":
![login page of deepin recovery](https://bbs.deepin.org/data/attachment/forum/201812/19/120328z2yuyp93qc9q73e3.jpg)

**Comment by BLumia** [comment]
Not quite sure about the deepin recovery environment, maybe @hualet can help :)

**Comment by LeanderChen** [comment]
Thank you for all of answers. And, I got another way by `ATIH`. Thank you.
