### ISSUE TITLE
Fixing Boot ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-clone#4]
Hi,

I found the following script in this project ...

boot_fix_x86.sh

can this script be run from live boot environment to fix boot issues on system with a corrupt boot ?

the procedure from here https://wiki.deepin.org/index.php?title=Repair_Boot ... does not fix corrupt grub.

thanks.

**Comment by zccrs** [comment]
Try: sudo deepin-clone -f /dev/xxx
The "xxx" is partition of system

**Comment by zccrs** [comment]
Sorry, it will work only in recovery mode

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
