### ISSUE TITLE
Cant build the master branch

### ISSUE THREAD

**Issue by yunusem** [linuxdeepin/deepin-clone#6]
[deepin-clone_0.0.1-1_amd64.build.txt](https://github.com/linuxdeepin/deepin-clone/files/1562554/deepin-clone_0.0.1-1_amd64.build.txt)
...
In file included from src/widgets/mainwindow.cpp:26:0:
src/corelib/helper.h: In instantiation of 'QString __d_asprintf__(const char*, Args&& ...) [with Args = {}]':
src/widgets/mainwindow.cpp:719:13:   required from here
src/corelib/helper.h:123:29: error: format not a string literal and no format arguments [-Werror=format-security]
     return QString::asprintf(format, std::forward<Args>(args)...);
            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
Makefile.deepin-clone-app:657: recipe for target 'mainwindow.o' failed
make[2]: *** [mainwindow.o] Error 1
make[2]: Leaving directory '/tmp/build-area/deepin-clone-1/app'
Makefile:43: recipe for target 'sub-app-deepin-clone-app-pro-make_first' failed
make[1]: *** [sub-app-deepin-clone-app-pro-make_first] Error 2
make[1]: Leaving directory '/tmp/build-area/deepin-clone-1'
dh_auto_build: make -j1 returned exit code 2
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 25
dpkg-buildpackage: error: debian/rules build gave error exit status 2


Any help ?

Thanx in advance.
Regards.

**Comment by zccrs** [comment]
fix: https://cr.deepin.io/#/c/32154/

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
