### ISSUE TITLE
Insufficient space?

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/deepin-clone#7]
Deepin clone says that the target partition has insufficient spaces even though it has a lot of spaces. Please fix this bug as soon as possible.

**Comment by zccrs** [comment]
This not is a bug, restore the target partition spaces can not be less than the source partition total spaces.

**Comment by rafaeldev** [comment]
I'm had this same problem.
When i try make a image using "Disk to Image" option this doesn't work.

1) Boot Deepin in Recovery mode
2) Open Deepin Clone
3) Select "Disk" option
4) Select "Disk to Image"; then next button
5) Select `/dev/sda` disk
6) Select `/dev/sba` hdd external; then clone button

**My hdd external has space 850 GB of free space and the partition should be cloned has 150 GB**

![deepinscreenshot_20180322032528](https://user-images.githubusercontent.com/4596160/37750848-c4c7bd4a-2d6d-11e8-81dc-15b9a06ec71e.png)
![deepinscreenshot_20180322032647](https://user-images.githubusercontent.com/4596160/37750861-c7a76826-2d6d-11e8-9514-6b52a65640d5.png)

**Comment by rafaeldev** [comment]
I tried do the backup again and it's works well!
@SiamSami , did you try to make backup again?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
